Feature "asm" has been stable since 1.59.0
The full error (this is the resultant fix):
```log
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> ./src/main.rs:1:12
  |
1 | #![feature(asm)]
  |            ^^^

warning: the feature `asm` has been stable since 1.59.0 and no longer requires an attribute to enable
 --> ./src/main.rs:1:12
  |
1 | #![feature(asm)]
  |            ^^^
  |
  = note: `#[warn(stable_features)]` on by default
```